#!/usr/bin/env python3
"""PreToolUse guard for the Dual-ExpFam LSM research repository.

Enforces the machine-checkable subset of the working rules in CLAUDE.md §6:
work happens on a branch (never directly on main), destructive/irreversible
Git operations stay under human control, and edits to frozen research
artifacts keep a confirmation boundary.

Design constraints (see GitHub Issue #13):
  * Python standard library ONLY. No jq, no third-party packages.
  * Reads the PreToolUse payload from stdin; uses the payload's `cwd`
    (never os.getcwd()) as the anchor for all Git queries.
  * Emits hookSpecificOutput.permissionDecision. The deprecated top-level
    `decision` / `approve` / `block` forms are not used.
  * Passing = no stdout, exit 0.
  * Ambiguity resolves to "ask", never to "deny".
  * Internal errors fail OPEN (exit 0 + stderr warning), so a broken guard
    never bricks a session. Safety therefore depends on this file staying
    intact; see the Limitations section in the Issue.

This is NOT a shell parser. It recognises high-confidence patterns only.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import sys

HOOK_EVENT = "PreToolUse"

EDIT_TOOLS = ("Edit", "Write", "NotebookEdit")
SHELL_TOOLS = ("Bash", "PowerShell")

PROTECTED_BRANCHES = ("main", "master")

# ---------------------------------------------------------------------------
# Protected paths (repo-root-relative, POSIX separators)
# ---------------------------------------------------------------------------

# Canonical docs and frozen manuscripts: the source of truth for the research.
CANONICAL_FILES = {
    "CLAUDE.md",
    "README.md",
    "RESEARCH_MASTER.md",
    "KNOWN_ISSUES.md",
    "EXPERIMENT_REGISTRY.md",
    "conference_submission_final_draft.md",
    "CLEANUP_MANIFEST.md",
}

# Historical records: dated, frozen, read as the record of their time.
HISTORICAL_FILES = {
    "START_HERE.md",
    "expfam/handoff.md",
}
HISTORICAL_PREFIXES = (
    "reports/",
    "docs/math_notes/",
    "docs/teacher/",
)

# Primary evidence: the baseline paper. Top of the source-priority order in
# CLAUDE.md §4, so it is protected on every branch.
PRIMARY_PREFIXES = ("paper/",)

# Research artifacts: generated by scripts, never hand-edited.
ARTIFACT_DIR_COMPONENTS = ("results", "figures")
ARTIFACT_SUFFIXES = (".csv", ".npy", ".npz")


def classify_protected(rel_posix: str) -> str | None:
    """Return a short reason if `rel_posix` is protected, else None."""
    if not rel_posix:
        return None
    parts = rel_posix.split("/")
    name = parts[-1]

    if rel_posix in CANONICAL_FILES:
        return "canonical document (source of truth)"
    for prefix in PRIMARY_PREFIXES:
        if rel_posix.startswith(prefix):
            return "primary source under %s (baseline paper)" % prefix
    if rel_posix in HISTORICAL_FILES:
        return "frozen historical record"
    for prefix in HISTORICAL_PREFIXES:
        if rel_posix.startswith(prefix):
            return "frozen historical record under %s" % prefix
    for component in ARTIFACT_DIR_COMPONENTS:
        if component in parts[:-1]:
            return "research artifact under a %s/ directory" % component
    if name.lower().endswith(ARTIFACT_SUFFIXES):
        return "research artifact (%s)" % os.path.splitext(name)[1]
    if "runinfo" in name.lower():
        return "experiment provenance record (runinfo)"
    return None


# ---------------------------------------------------------------------------
# Git helpers (anchored on the payload's cwd)
# ---------------------------------------------------------------------------


class GitUnavailable(Exception):
    """Raised when git itself could not be executed."""


def _git(cwd: str, *args: str) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            ["git", "-C", cwd, *args],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise GitUnavailable(str(exc)) from exc
    return proc.returncode, (proc.stdout or "").strip()


def repo_root(cwd: str) -> str | None:
    """Absolute repo root, or None when cwd is not inside a work tree."""
    code, out = _git(cwd, "rev-parse", "--show-toplevel")
    if code != 0 or not out:
        return None
    return os.path.normpath(out)


def current_branch(cwd: str) -> str | None:
    """Branch name, or None when detached / undeterminable."""
    code, out = _git(cwd, "rev-parse", "--abbrev-ref", "HEAD")
    if code != 0 or not out or out == "HEAD":
        return None
    return out


# ---------------------------------------------------------------------------
# Path normalisation
# ---------------------------------------------------------------------------


def to_repo_relative(raw_path: str, cwd: str, root: str) -> str | None:
    """Normalise a tool-supplied path to a repo-root-relative POSIX path.

    Returns None when the path resolves outside the repository, so that
    scratchpad/temp work is never blocked by the repo-scoped invariants.
    """
    if not raw_path:
        return None
    candidate = raw_path.replace("\\", "/")
    if not os.path.isabs(candidate):
        candidate = os.path.join(cwd, candidate)
    candidate = os.path.normpath(candidate)
    try:
        rel = os.path.relpath(candidate, root)
    except ValueError:
        # Different drive letters on Windows.
        return None
    rel = rel.replace("\\", "/")
    if rel == ".." or rel.startswith("../"):
        return None
    return rel


def looks_like_repo_path(token: str, cwd: str, root: str) -> str | None:
    """Best-effort repo-relative path for a shell token, else None."""
    stripped = token.strip().strip("'\"")
    if not stripped or stripped.startswith("-"):
        return None
    return to_repo_relative(stripped, cwd, root)


# ---------------------------------------------------------------------------
# Shell segmentation and tokenisation (deliberately approximate)
# ---------------------------------------------------------------------------

_SEGMENT_SPLIT = re.compile(r"&&|\|\||[;\n|]")


def split_segments(command: str) -> list[str]:
    """Split a command line into statement-ish segments, respecting quotes."""
    segments: list[str] = []
    buf: list[str] = []
    quote: str | None = None
    i = 0
    while i < len(command):
        ch = command[i]
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in "'\"":
            quote = ch
            buf.append(ch)
            i += 1
            continue
        two = command[i : i + 2]
        if two in ("&&", "||"):
            segments.append("".join(buf))
            buf = []
            i += 2
            continue
        if ch in ";\n|":
            segments.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    segments.append("".join(buf))
    return [s.strip() for s in segments if s.strip()]


POSIX_KIND = "posix"
WINDOWS_KIND = "windows"


def unquote(token: str) -> str:
    tok = token.strip()
    if len(tok) >= 2 and tok[0] == tok[-1] and tok[0] in "'\"":
        return tok[1:-1]
    return tok


def tokenize(segment: str, kind: str = POSIX_KIND) -> list[str]:
    """Tokenise one segment with the lexer that matches the shell.

    POSIX mode treats backslash as an escape, which silently destroys Windows
    paths such as ``reports\\a.md``. Windows-flavoured shells therefore get
    posix=False first; Bash keeps posix=True first.
    """
    orders = (False, True) if kind == WINDOWS_KIND else (True, False)
    for posix in orders:
        try:
            return shlex.split(segment, posix=posix)
        except ValueError:
            continue
    return segment.split()


def basename_of(token: str) -> str:
    name = unquote(token).replace("\\", "/").rsplit("/", 1)[-1].lower()
    for suffix in (".exe", ".cmd", ".bat", ".ps1"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    return name


# Common interpreter wrappers. Only these exact shapes are unwrapped, at most
# MAX_WRAPPER_DEPTH levels deep. This is not a shell parser.
MAX_WRAPPER_DEPTH = 2

WRAPPER_SPECS = {
    "powershell": ({"-command", "-c"}, WINDOWS_KIND),
    "pwsh": ({"-command", "-c"}, WINDOWS_KIND),
    "cmd": ({"/c", "/k"}, WINDOWS_KIND),
    "bash": ({"-c", "-lc", "-ic", "-lic"}, POSIX_KIND),
    "sh": ({"-c", "-lc"}, POSIX_KIND),
    "zsh": ({"-c", "-lc"}, POSIX_KIND),
}


def extract_wrapper(tokens: list[str]) -> tuple[str, str] | None:
    """Return (inner command string, inner shell kind) for a known wrapper."""
    if not tokens:
        return None
    spec = WRAPPER_SPECS.get(basename_of(tokens[0]))
    if spec is None:
        return None
    flags, inner_kind = spec
    for i in range(1, len(tokens) - 1):
        if unquote(tokens[i]).lower() in flags:
            inner = unquote(tokens[i + 1])
            return (inner, inner_kind) if inner.strip() else None
    return None


# ---------------------------------------------------------------------------
# Command recognisers
# ---------------------------------------------------------------------------

GIT_VALUE_OPTIONS = {"-C", "-c", "--git-dir", "--work-tree", "--namespace", "--exec-path"}


def git_subcommand(tokens: list[str]) -> tuple[str | None, list[str]]:
    """Return (subcommand, remaining args), skipping git's global options."""
    i = 1
    while i < len(tokens):
        tok = tokens[i]
        if tok in GIT_VALUE_OPTIONS:
            i += 2
            continue
        if tok.startswith("-"):
            i += 1
            continue
        return tok, tokens[i + 1 :]
    return None, []


def short_flag_chars(args: list[str]) -> set[str]:
    """Characters from bundled single-dash flags, e.g. -fdx -> {f,d,x}."""
    chars: set[str] = set()
    for arg in args:
        if arg.startswith("-") and not arg.startswith("--") and len(arg) > 1:
            chars.update(arg[1:])
    return chars


PYTHON_NAMES = {"python", "python3", "py", "python3.13", "python.exe"}
PIP_NAMES = {"pip", "pip3", "pip3.13"}

# Write indicators inside `python -c` code. Deliberately narrow: an open()
# call whose mode argument requests writing, or an unambiguous write API.
PY_WRITE_PATTERNS = (
    re.compile(r"open\s*\([^)]*,\s*['\"][^'\"]*[wax+]"),
    re.compile(r"\.write_text\s*\("),
    re.compile(r"\.write_bytes\s*\("),
    re.compile(r"\.to_csv\s*\("),
    re.compile(r"\.savefig\s*\("),
    re.compile(r"\bnp\.save(?:z|txt)?\s*\("),
    re.compile(r"\bos\.(remove|unlink|rename|replace|rmdir)\s*\("),
    re.compile(r"\bshutil\.(copy\w*|move|rmtree)\s*\("),
)

# Shell verbs that write. Value = which tokens are treated as targets.
POSIX_WRITE_VERBS = {
    "cp": "last",
    "mv": "last",
    "rm": "all",
    "install": "last",
    "truncate": "all",
    "tee": "all",
    "dd": "all",
}
PS_WRITE_VERBS = {
    "set-content": "all",
    "add-content": "all",
    "out-file": "all",
    "remove-item": "all",
    "clear-content": "all",
    "move-item": "last",
    "copy-item": "last",
    "new-item": "all",
    "tee-object": "all",
}

_REDIRECT = re.compile(r">>?\s*([^\s;|&<>]+)")


def redirect_targets(segment: str) -> list[str]:
    return [m.group(1) for m in _REDIRECT.finditer(segment)]


# ---------------------------------------------------------------------------
# Findings
# ---------------------------------------------------------------------------


class Finding:
    __slots__ = ("decision", "reason")

    def __init__(self, decision: str, reason: str) -> None:
        self.decision = decision
        self.reason = reason


RANK = {"ask": 1, "deny": 2}


def strongest(findings: list[Finding]) -> Finding | None:
    if not findings:
        return None
    return max(findings, key=lambda f: RANK.get(f.decision, 0))


# ---------------------------------------------------------------------------
# Invariant A: Edit / Write / NotebookEdit
# ---------------------------------------------------------------------------


def evaluate_edit(tool_input: dict, cwd: str) -> Finding | None:
    raw_path = (
        tool_input.get("file_path")
        or tool_input.get("notebook_path")
        or tool_input.get("path")
        or ""
    )

    try:
        root = repo_root(cwd)
    except GitUnavailable as exc:
        return Finding(
            "ask",
            "Could not determine the Git branch (git unavailable: %s). "
            "The main-branch edit guard cannot be evaluated, so this edit "
            "needs human confirmation." % exc,
        )

    if root is None:
        # Not inside a work tree: nothing repo-scoped to protect.
        return None

    rel = to_repo_relative(raw_path, cwd, root)
    if rel is None:
        # Target lives outside the repository (scratchpad, temp, ...).
        return None

    branch = current_branch(cwd)

    if branch is None:
        return Finding(
            "ask",
            "Git branch could not be determined (detached HEAD or git error). "
            "CLAUDE.md §6 forbids editing on main; confirm the branch before "
            "writing to '%s'." % rel,
        )

    if branch in PROTECTED_BRANCHES:
        return Finding(
            "deny",
            "Refusing to edit '%s' while on branch '%s'. CLAUDE.md §6: never "
            "edit main directly — create a working branch first "
            "(git switch -c <type>/<issue#>-<slug>)." % (rel, branch),
        )

    reason = classify_protected(rel)
    if reason:
        return Finding(
            "ask",
            "'%s' is a %s. Confirm this change is an intended append/addition "
            "and not a rewrite of an existing record (CLAUDE.md §6, KNOWN_ISSUES "
            "KI-007/KI-014)." % (rel, reason),
        )

    return None


# ---------------------------------------------------------------------------
# Invariant B: Bash / PowerShell
# ---------------------------------------------------------------------------


def evaluate_git_segment(
    tokens: list[str], branch: str | None, findings: list[Finding]
) -> None:
    sub, args = git_subcommand(tokens)
    if sub is None:
        return

    if sub == "commit" and branch in PROTECTED_BRANCHES:
        findings.append(
            Finding(
                "deny",
                "Refusing 'git commit' on branch '%s'. CLAUDE.md §6: commit on a "
                "working branch, never on main." % branch,
            )
        )

    if sub == "push":
        forced = False
        for arg in args:
            if arg == "-f" or arg.startswith("--force"):
                forced = True
            elif arg.startswith("+") and not arg.startswith("-"):
                forced = True  # forced refspec, e.g. origin +main
        if not forced and "f" in short_flag_chars(args):
            forced = True
        if forced:
            findings.append(
                Finding(
                    "deny",
                    "Refusing a force push. Rewriting published history destroys "
                    "experiment provenance; if a force push is genuinely needed, "
                    "run it yourself.",
                )
            )

    if sub == "clean":
        flags = short_flag_chars(args)
        dry_run = "n" in flags or "--dry-run" in args
        forced = "f" in flags or "--force" in args
        if forced and not dry_run:
            findings.append(
                Finding(
                    "deny",
                    "Refusing 'git clean --force'. Untracked result artifacts and "
                    "machine-local settings are not recoverable once deleted. Use "
                    "'git clean -n' to preview instead.",
                )
            )

    if sub == "reset" and ("--hard" in args):
        findings.append(
            Finding(
                "ask",
                "'git reset --hard' discards uncommitted work in the working tree. "
                "Confirm this is intended.",
            )
        )


# gh options that consume the following token. Without these, a legitimate
# invocation such as `gh --repo O/R pr merge 123` would hide the subcommand.
GH_VALUE_OPTIONS = {
    "--repo", "-R", "--hostname", "--json", "--jq", "-q",
    "--template", "-t", "--limit", "-L", "--body", "-b", "--title",
}


def gh_positionals(tokens: list[str]) -> list[str]:
    """Positional arguments of a gh command, with options and values removed."""
    out: list[str] = []
    i = 1
    while i < len(tokens):
        tok = unquote(tokens[i])
        if tok in GH_VALUE_OPTIONS:
            i += 2
            continue
        if tok.startswith("-"):
            i += 1
            continue
        out.append(tok)
        i += 1
    return out


def evaluate_gh_segment(tokens: list[str], findings: list[Finding]) -> None:
    positionals = gh_positionals(tokens)
    if (
        len(positionals) >= 2
        and positionals[0] == "pr"
        and positionals[1] in ("merge", "close")
    ):
        findings.append(
            Finding(
                "deny",
                "Refusing 'gh pr %s'. Merging or closing a pull request is a human "
                "decision and must not be automated." % positionals[1],
            )
        )


def evaluate_pip_segment(tokens: list[str], findings: list[Finding]) -> None:
    names = [basename_of(t) for t in tokens]
    action = None
    if names and names[0] in PIP_NAMES:
        rest = [t for t in tokens[1:] if not t.startswith("-")]
        action = rest[0] if rest else None
    elif names and names[0] in PYTHON_NAMES and "-m" in tokens:
        idx = tokens.index("-m")
        if idx + 1 < len(tokens) and basename_of(tokens[idx + 1]) in PIP_NAMES:
            rest = [t for t in tokens[idx + 2 :] if not t.startswith("-")]
            action = rest[0] if rest else None
    if action in ("install", "uninstall"):
        findings.append(
            Finding(
                "ask",
                "'pip %s' changes the Python environment. The reproducibility "
                "baseline is pinned by requirements*.txt / .python-version "
                "(KNOWN_ISSUES KI-014); confirm before altering it." % action,
            )
        )


def evaluate_python_inline(
    tokens: list[str], branch: str | None, findings: list[Finding]
) -> None:
    if not tokens or basename_of(tokens[0]) not in PYTHON_NAMES:
        return
    if "-c" not in tokens:
        return
    idx = tokens.index("-c")
    if idx + 1 >= len(tokens):
        return
    code = tokens[idx + 1]
    if not any(pat.search(code) for pat in PY_WRITE_PATTERNS):
        return
    on_main = branch in PROTECTED_BRANCHES
    findings.append(
        Finding(
            "ask",
            "This inline 'python -c' appears to write to the filesystem%s. Inline "
            "writes bypass the Edit/Write guard; confirm the target, or use a "
            "script under version control."
            % (" while on branch '%s'" % branch if on_main else ""),
        )
    )


def evaluate_shell_writes(
    segment: str,
    tokens: list[str],
    branch: str | None,
    cwd: str,
    root: str | None,
    findings: list[Finding],
) -> None:
    """Flag high-confidence writes: to protected paths anywhere, or anywhere on main."""
    if not tokens:
        return
    verb = basename_of(tokens[0])
    on_main = branch in PROTECTED_BRANCHES

    targets: list[str] = list(redirect_targets(segment))
    mode = POSIX_WRITE_VERBS.get(verb) or PS_WRITE_VERBS.get(verb)

    if verb == "sed" and any(a == "-i" or a.startswith("-i") for a in tokens[1:]):
        mode = "all"

    if mode:
        candidates = [t for t in tokens[1:] if not t.startswith("-")]
        if mode == "last" and candidates:
            targets.extend(candidates[-1:])
        elif mode == "all":
            targets.extend(candidates)

    if not targets:
        return

    if root is not None:
        for target in targets:
            rel = looks_like_repo_path(target, cwd, root)
            if rel is None:
                continue
            reason = classify_protected(rel)
            if reason:
                findings.append(
                    Finding(
                        "ask",
                        "This shell command writes to '%s', a %s. Results and frozen "
                        "records are regenerated by scripts, not edited (CLAUDE.md §6)."
                        % (rel, reason),
                    )
                )
                return

    if on_main:
        findings.append(
            Finding(
                "ask",
                "This shell command writes to the filesystem while on branch '%s'. "
                "CLAUDE.md §6 forbids working directly on main; confirm the target."
                % branch,
            )
        )


def evaluate_command(
    command: str,
    kind: str,
    branch: str | None,
    cwd: str,
    root: str | None,
    findings: list[Finding],
    depth: int = 0,
) -> None:
    """Evaluate one command line, descending into recognised shell wrappers.

    Wrapper descent is bounded by MAX_WRAPPER_DEPTH. The outer segment is still
    evaluated after a descent, so a redirection on the wrapper itself is not
    lost. Arbitrary interpreter payloads (notably `python -c`) are deliberately
    NOT parsed for nested commands; the project-level `ask` rules in
    .claude/settings.json own that boundary.
    """
    for segment in split_segments(command):
        tokens = tokenize(segment, kind)
        if not tokens:
            continue
        head = basename_of(tokens[0])

        if depth < MAX_WRAPPER_DEPTH:
            wrapped = extract_wrapper(tokens)
            if wrapped is not None:
                inner, inner_kind = wrapped
                evaluate_command(
                    inner, inner_kind, branch, cwd, root, findings, depth + 1
                )

        if head == "git":
            evaluate_git_segment(tokens, branch, findings)
        elif head == "gh":
            evaluate_gh_segment(tokens, findings)

        evaluate_pip_segment(tokens, findings)
        evaluate_python_inline(tokens, branch, findings)
        evaluate_shell_writes(segment, tokens, branch, cwd, root, findings)


def evaluate_shell(tool_input: dict, cwd: str, tool_name: str) -> Finding | None:
    command = tool_input.get("command") or ""
    if not isinstance(command, str) or not command.strip():
        return None

    try:
        root = repo_root(cwd)
    except GitUnavailable:
        root = None
    try:
        branch = current_branch(cwd) if root is not None else None
    except GitUnavailable:
        branch = None

    kind = WINDOWS_KIND if tool_name == "PowerShell" else POSIX_KIND
    findings: list[Finding] = []
    evaluate_command(command, kind, branch, cwd, root, findings)
    return strongest(findings)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def emit(finding: Finding) -> None:
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": HOOK_EVENT,
                "permissionDecision": finding.decision,
                "permissionDecisionReason": finding.reason,
            }
        },
        sys.stdout,
    )
    sys.stdout.write("\n")


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception as exc:  # malformed or empty stdin
        print("research_guard: unreadable hook payload (%s); failing open" % exc,
              file=sys.stderr)
        return 0

    if not isinstance(payload, dict):
        print("research_guard: unexpected payload type; failing open", file=sys.stderr)
        return 0

    tool_name = payload.get("tool_name") or ""
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        tool_input = {}
    cwd = payload.get("cwd") or os.getcwd()
    if not os.path.isdir(cwd):
        cwd = os.getcwd()

    try:
        if tool_name in EDIT_TOOLS:
            finding = evaluate_edit(tool_input, cwd)
        elif tool_name in SHELL_TOOLS:
            finding = evaluate_shell(tool_input, cwd, tool_name)
        else:
            finding = None
    except Exception as exc:  # never brick a session on a guard bug
        print("research_guard: internal error (%r); failing open" % exc, file=sys.stderr)
        return 0

    if finding is not None:
        emit(finding)
    return 0


if __name__ == "__main__":
    sys.exit(main())
